export const tableData = [
  {
    id: 1,
    title: "রহমতের ১০ দিন",
    time: [
      {
        id: 1,
        serial: '01',
        englishMonth: "০৩ এপ্রিল",
        day: "রবিবার",
        saheri: "৪:২৭",
        iftar: "৬:১৯",
      },
      {
        id: 2,
        serial: '02',
        englishMonth: "০৪ এপ্রিল",
        day: "সোমবার",
        saheri: "৪:২৬",
        iftar: "৬:১৯",
      },
      {
        id: 3,
        serial: '03',
        englishMonth: "০৫ এপ্রিল",
        day: "মঙ্গলবার",
        saheri: "৪:২৪",
        iftar: "৬:২০",
      },
      {
        id: 4,
        serial: '04',
        englishMonth: "০৬ এপ্রিল",
        day: "বুধবার",
        saheri: "৪:২৪",
        iftar: "৬:২০",
      },
      {
        id: 5,
        serial: '05',
        englishMonth: "০৭ এপ্রিল",
        day: "বৃহস্পতিবার",
        saheri: "৪:২৩",
        iftar: "৬:২১",
      },
      {
        id: 6,
        serial: '06',
        englishMonth: "০৮ এপ্রিল",
        day: "শুক্রবার",
        saheri: "৪:২২",
        iftar: "৬:২১",
      },
      {
        id: 7,
        serial: '07',
        englishMonth: "০৯ এপ্রিল",
        day: "শনিবার",
        saheri: "৪:২১",
        iftar: "৬:২১",
      },
      {
        id: 8,
        serial: '08',
        englishMonth: "১০ এপ্রিল",
        day: "রবিবার",
        saheri: "৪:২০",
        iftar: "৬:২২",
      },
      {
        id: 9,
        serial: '09',
        englishMonth: "১১ এপ্রিল",
        day: "সোমবার",
        saheri: "৪:১৯",
        iftar: "৬:২২",
      },
      {
        id: 10,
        serial: '10',
        englishMonth: "১২ এপ্রিল",
        day: "মঙ্গলবার",
        saheri: "৪:১৮",
        iftar: "৬:২৩",
      },
    ],
  },
  {
    id: 2,
    title: "মাগফিরাতের ১০ দিন",
    time: [
      {
        id: 11,
        serial: '11',
        englishMonth: "১৩ এপ্রিল",
        day: "বুধবার",
        saheri: "৪:১৭",
        iftar: "৬:২৩",
      },
      {
        id: 12,
        serial: '12',
        englishMonth: "১৪ এপ্রিল",
        day: "বৃহস্পতিবার",
        saheri: "৪:১৫",
        iftar: "৬:২৩",
      },
      {
        id: 13,
        serial: '13',
        englishMonth: "১৫ এপ্রিল",
        day: "শুক্রবার",
        saheri: "৪:১৪",
        iftar: "৬:২৪",
      },
      {
        id: 14,
        serial: '14',
        englishMonth: "১৬ এপ্রিল",
        day: "শনিবার",
        saheri: "৪:১৩",
        iftar: "৬:২৪",
      },
      {
        id: 15,
        serial: '15',
        englishMonth: "১৭ এপ্রিল",
        day: "রবিবার",
        saheri: "৪:১২",
        iftar: "৬:২৪",
      },
      {
        id: 16,
        serial: '16',
        englishMonth: "১৮ এপ্রিল",
        day: "সোমবার",
        saheri: "৪:১১",
        iftar: "৬:২৫",
      },
      {
        id: 17,
        serial: '17',
        englishMonth: "১৯ এপ্রিল",
        day: "মঙ্গলবার",
        saheri: "৪:১০",
        iftar: "৬:২৫",
      },
      {
        id: 18,
        serial: '18',
        englishMonth: "২০ এপ্রিল",
        day: "বুধবার",
        saheri: "৪:০৯",
        iftar: "৬:২৬",
      },
      {
        id: 19,
        serial: '19',
        englishMonth: "২১ এপ্রিল",
        day: "বৃহস্পতিবার",
        saheri: "৪:০৮",
        iftar: "৬:২৬",
      },
      {
        id: 20,
        serial: '20',
        englishMonth: "২২ এপ্রিল",
        day: "শুক্রবার",
        saheri: "৪:০৭",
        iftar: "৬:২৭",
      },
    ],
  },
  {
    id: 3,
    title: "নাজাতের ১০ দিন",
    time: [
      {
        id: 21,
        serial: '21',
        englishMonth: "২৩ এপ্রিল",
        day: "শনিবার",
        saheri: "৪:০৬",
        iftar: "৬:২৭",
      },
      {
        id: 22,
        serial: '22',
        englishMonth: "২৪ এপ্রিল",
        day: "রবিবার",
        saheri: "৪:০৫",
        iftar: "৬:২৮",
      },
      {
        id: 23,
        serial: '23',
        englishMonth: "২৫ এপ্রিল",
        day: "সোমবার",
        saheri: "৪:০৫",
        iftar: "৬:২৮",
      },
      {
        id: 24,
        serial: '24',
        englishMonth: "২৬ এপ্রিল",
        day: "মঙ্গলবার",
        saheri: "৪:০৪",
        iftar: "৬:২৯",
      },
      {
        id: 25,
        serial: '25',
        englishMonth: "২৭ এপ্রিল",
        day: "বুধবার",
        saheri: "৪:০৩",
        iftar: "৬:২৯",
      },
      {
        id: 26,
        serial: '26',
        englishMonth: "২৮ এপ্রিল",
        day: "বৃহস্পতিবার",
        saheri: "৪:০২",
        iftar: "৬:২৯",
      },
      {
        id: 27,
        serial: '27',
        englishMonth: "২৯ এপ্রিল",
        day: "শুক্রবার",
        saheri: "৪:০১",
        iftar: "৬:৩০",
      },
      {
        id: 28,
        serial: '28',
        englishMonth: "৩০ এপ্রিল",
        day: "শনিবার",
        saheri: "৪:০০",
        iftar: "৬:৩০",
      },
      {
        id: 29,
        serial: '29',
        englishMonth: "০১ মে",
        day: "রবিবার",
        saheri: "৩:৫৯",
        iftar: "৬:৩১",
      },
      {
        id: 30,
        serial: '30',
        englishMonth: "০২ মে",
        day: "সোমবার",
        saheri: "৩:৫৮",
        iftar: "৬:৩১",
      },
    ],
  },
];
