import Head from "next/head";

export default function Home() {
  return (
    <div className="max-w-screen-lg mx-auto h-screen bg-slate-400 full_container">
      <Head>
        <title>Welcome To Ramadan Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative">
          <div className="absolute top-2/4 left-[44%]">
            <h1 className="text-2xl font-sans font-bold"></h1>
            <h1 className="text-2xl title">তোহফায়ে রমযানুল মোবারক</h1>
          </div>
        </div>
      </main>
    </div>
  );
}
